### PR TITLE
stack

### PR DESCRIPTION
**Pull request by kavitha235**

### CODE REVIEW

**Comment by kgashok** [comment]
Good suggestion, but probably appropriate in a data structure specific glossary.

**Comment by vinithmenon** [comment]
A server stack is one type of solution stack -- an ordered selection of software that makes it possible to complete a particular task. A client stack includes the operating system (OS) and its supporting software as well as runtime environments, such as the Java Runtime Environment

**Comment by kgashok** [comment]
@vinithmenon you are suggesting an IMS term into a Computer Science glossary. Think about putting out a Computer Security glossary, that would be in-line with the focus that IMS will have for the student body.

**Comment by vinithmenon** [comment]
Sir Sure I shall do it

**Pull request closed without merging**
